# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

transient_prompt:
  template: " ❯ "
  foreground_templates:
  - "{{if gt .Code 0}}#ff6e5e{{end}}"
  - "{{if eq .Code 0}}#ff5ef1{{end}}"
blocks:
- type: prompt
  alignment: left
  segments:
  - properties:
      style: austin
      threshold: 150.0
    style: plain
    template: "{{ .FormattedMs }}"
    foreground: "#7b8496"
    type: executiontime
  - properties:
      style: folder
    style: plain
    template: "    {{ .Path }}"
    foreground: "#5eff6c"
    type: path
  - properties:
      branch_max_length: 25.0
      fetch_status: true
    style: plain
    template: "{{ .UpstreamIcon }} {{ .HEAD }} {{if .BranchStatus }} {{ .BranchStatus }}{{ end }} "
    foreground: "#5ef1ff"
    type: git
    foreground_templates:
    - "{{ if or (.Working.Changed) (.Staging.Changed) }}#ffbd5e{{ end }}"
    - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff6e5e{{ end }}"
    - "{{ if gt .Ahead 0 }}#bd5eff{{ end }}"
    - "{{ if gt .Behind 0 }}#bd5eff{{ end }}"
  
  newline: true
version: 3
auto_upgrade: true
final_space: true
