search_submodules = true
session_sort_order = "LastAttached"
bookmarks = [
    "/Users/josevelazquez/dotfiles",
    "/Users/josevelazquez/projects",
    "/Users/josevelazquez/dotfiles/.config/nvim",
    "/Users/josevelazquez",
]

[[search_dirs]]
path = "/Users/josevelazquez/work/projects"
depth = 10
