search_submodules = true
session_sort_order = "LastAttached"
bookmarks = [
    "~/dotfiles",
    "~/projects",
    "~/dotfiles/.config/nvim",
    "~/",
]

[[search_dirs]]
path = "~/projects"
depth = 10
